# Generated by Django 4.2 on 2023-04-16 12:14

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Задание")),
                ("description", models.TextField(verbose_name="Описание")),
                ("deadline", models.DateField(verbose_name="Дата завершения")),
                (
                    "is_complete",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
            bases=(models.Model, todo_app.models.DateTimeMixin),
        ),
    ]
